### ISSUE TITLE
특정 계정으로 비밀번호 초기화 요청시 에러 발생

### ISSUE THREAD

**Issue by Kasania** [sjy5386/subshorts#1]
admin@subshorts.com 의 계정으로 비밀번호 초기화 요청을 전송하는경우 500에러가 발생합니다.

**Comment by Kasania** [comment]
꼭 특정 계정이 아니라 가입되어 있는 계정에 요청을 보내는 경우 에러가 발생합니다.
이를 통하여 가입되어있는 계정의 이메일 정보를 확인 해낼수 있습니다.

**Comment by sjy5386** [comment]
서버에 SMTP 계정 설정을 했습니다.
